services:

  blazor:
    build: ./Blazor
    container_name: blazor-frontend
    ports:
      - "8080:80"
    depends_on:
      - searchapi
    volumes:
      - ./seData_copy/medium.db:/app/data/medium.db
    environment:
      - DATABASE_PATH=/app/data/medium.db

  searchapi:
    build:
      context: .
      dockerfile: SearchApi/Dockerfile
    container_name: search-api
    ports:
      - "5000:8080"
    volumes:
      - ./seData_copy/medium.db:/app/data/medium.db
    environment:
      - DATABASE_PATH=/app/data/medium.db

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    container_name: indexer-worker
    depends_on:
      - searchapi
    volumes:
      - ./seData_copy/medium:/app/input
      - ./seData_copy/medium.db:/app/data/medium.db
    environment:
      - DATABASE_PATH=/app/data/medium.db
      - INPUT_FOLDER=/app/input

  loadbalancer:
    build: ./LoadBalancerAPI
    container_name: loadbalancer
    ports:
      - "9000:9090"
    depends_on:
      - searchapi

  consolesearch:
    build:
      context: .
      dockerfile: ConsoleSearch/Dockerfile
    container_name: consolesearch
    ports:
      - "6000:8080"
    volumes:
      - ./seData_copy/medium.db:/app/data/medium.db
    environment:
    - DATABASE_PATH=/app/data/medium.db
